// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLn5KUscLua0dP7TroXBW13A9A0rGGG6c',
    appId: '1:281774571125:web:d92323b4b75ec50ce7c23c',
    messagingSenderId: '281774571125',
    projectId: 'flutterfire-tomaash',
    authDomain: 'flutterfire-tomaash.firebaseapp.com',
    storageBucket: 'flutterfire-tomaash.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYmw-sL5JcKHUCUdDyglxdMv3VMAaz4k',
    appId: '1:281774571125:android:6418b019c0c8859ce7c23c',
    messagingSenderId: '281774571125',
    projectId: 'flutterfire-tomaash',
    storageBucket: 'flutterfire-tomaash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwrJ3Sf_FGOloZfnIq0bqTkZyK51xlOGY',
    appId: '1:281774571125:ios:0dbb8b5b38ba46d1e7c23c',
    messagingSenderId: '281774571125',
    projectId: 'flutterfire-tomaash',
    storageBucket: 'flutterfire-tomaash.firebasestorage.app',
    iosBundleId: 'com.example.flutterfireGame',
  );
}
